[project]
name = "dbrx-snippets"
version = "0.1.0"
description = "snippets for llms"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databricks-feature-engineering>=0.10.2",
    "databricks-sdk>=0.49.0",
    "mlflow>=2.21.3",
]
